name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      # # - name: Install dependencies test
      # #   run: |
      # #     pip install flake8 bandit flasgger pyyaml

      - name: Install dependencies
        run: |
          pip install bandit flasgger pyyaml

      # - name: Lint code
      #   run: flake8 .

      - name: Check security
        run: bandit -r .

      - name: Generate OpenAPI documentation
        run: python generate_openapi.py

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Install Redocly 
        run: npm i -g @redocly/cli@latest
        
      - name: Build documentation with Redocly
        run: redocly build-docs docs/openapi.yaml --output docs/redoc-static.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  
          publish_branch: gh-pages  
          keep_files: true
