name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install flake8 pytest pytest-cov bandit

      - name: Check security
        run: bandit -r .

      - name: Generate OpenAPI documentation
        run: |
          python generate_openapi.py
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Install Redocly
        run: npm install -g @redocly/cli@latest
        
      - name: Build documentation with Redocly
        run: redocly build-docs openapi.yaml # Убедитесь, что файл openapi.yaml создан

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # Убедитесь, что здесь правильный путь к сгенерированным файлам документации
          publish_branch: gh-pages
          keep_files: true
